name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Run tests
        run: |
          echo "Running tests..."
          exit 0  # Hoặc exit 1 tùy vào kết quả bạn muốn giả lập
          
      # Bước actions/checkout đã bị loại bỏ.
