jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      # Removed steps related to running backend and frontend
      # Adjust or add your own steps based on your new project setup
      - name: Run application (example command)
        run: npm run build  # Replace with your desired command (e.g., build or test)
